chain together truffle, abi-gen, and tsc (ERRORS!)
toolchain assembled but there are quite a few errors emitted from the
typescript compiler, shown below.

yarn run v1.7.0
$ yarn abi-gen
$ truffle compile
$ abi-gen --abis 'build/contracts/*.json' --out build/types --template contract_templates/contract.handlebars --partials 'contract_templates/partials/*.handlebars'
Found 7 partial templates
Found 1 ABI files
Processing: Migrations...
Created: build/types/migrations.ts
$ tsc
build/types/migrations.ts(12,25): error TS7016: Could not find a declaration file for module 'ethers'. '/home/gene/truffletmp/node_modules/ethers/index.js' implicitly has an 'any' type.
  Try `npm install @types/ethers` if it exists or add a new declaration (.d.ts) file containing `declare module 'ethers';`
build/types/migrations.ts(13,20): error TS7016: Could not find a declaration file for module 'lodash'. '/home/gene/truffletmp/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`
build/types/migrations.ts(22,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
build/types/migrations.ts(50,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
build/types/migrations.ts(78,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
build/types/migrations.ts(81,23): error TS1013: A rest parameter or binding pattern may not have a trailing comma.
build/types/migrations.ts(105,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
build/types/migrations.ts(108,23): error TS1013: A rest parameter or binding pattern may not have a trailing comma.
build/types/migrations.ts(130,23): error TS1013: A rest parameter or binding pattern may not have a trailing comma.
build/types/migrations.ts(143,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
build/types/migrations.ts(146,25): error TS1013: A rest parameter or binding pattern may not have a trailing comma.
build/types/migrations.ts(170,12): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
build/types/migrations.ts(173,25): error TS1013: A rest parameter or binding pattern may not have a trailing comma.
build/types/migrations.ts(195,25): error TS1013: A rest parameter or binding pattern may not have a trailing comma.
build/types/migrations.ts(208,8): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
build/types/migrations.ts(221,8): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
node_modules/@0xproject/base-contract/lib/src/index.d.ts(1,23): error TS2688: Cannot find type definition file for 'ethers'.
node_modules/@0xproject/base-contract/lib/src/index.d.ts(4,25): error TS7016: Could not find a declaration file for module 'ethers'. '/home/gene/truffletmp/node_modules/ethers/index.js' implicitly has an 'any' type.
  Try `npm install @types/ethers` if it exists or add a new declaration (.d.ts) file containing `declare module 'ethers';`
node_modules/@0xproject/base-contract/node_modules/@0xproject/web3-wrapper/lib/src/web3_wrapper.d.ts(1,23): error TS2688: Cannot find type definition file for 'web3'.
node_modules/@0xproject/base-contract/node_modules/@0xproject/web3-wrapper/lib/src/web3_wrapper.d.ts(4,23): error TS7016: Could not find a declaration file for module 'web3'. '/home/gene/truffletmp/node_modules/web3/index.js' implicitly has an 'any' type.
  Try `npm install @types/web3` if it exists or add a new declaration (.d.ts) file containing `declare module 'web3';`
node_modules/@0xproject/sol-compiler/lib/src/utils/types.d.ts(1,23): error TS2688: Cannot find type definition file for 'solc'.
node_modules/@0xproject/sol-compiler/lib/src/utils/types.d.ts(3,23): error TS7016: Could not find a declaration file for module 'solc'. '/home/gene/truffletmp/node_modules/solc/index.js' implicitly has an 'any' type.
  Try `npm install @types/solc` if it exists or add a new declaration (.d.ts) file containing `declare module 'solc';`
node_modules/@0xproject/web3-wrapper/lib/src/web3_wrapper.d.ts(1,23): error TS2688: Cannot find type definition file for 'web3'.
node_modules/@0xproject/web3-wrapper/lib/src/web3_wrapper.d.ts(4,23): error TS7016: Could not find a declaration file for module 'web3'. '/home/gene/truffletmp/node_modules/web3/index.js' implicitly has an 'any' type.
  Try `npm install @types/web3` if it exists or add a new declaration (.d.ts) file containing `declare module 'web3';`
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.